import 'package:flutter/material.dart';

import '../pos.dart';


final List<Product> products = [
  Product(
    name: 'Coca-Cola',
    barcode: '9876543210123',
    quantity: '100',
    category: 'Beverages',
    salePrice: '10 EGP',
    purchasePrice: '7 EGP',
    description: 'Soft Drink',
    expirationDate: '2024-01-01',
    imagePath: 'assets/images/5.jpeg',
  ),
  Product(
    name: 'Pepsi',
    barcode: '9876543210124',
    quantity: '80',
    category: 'Beverages',
    salePrice: '10 EGP',
    purchasePrice: '6.5 EGP',
    description: 'Carbonated Soft Drink',
    expirationDate: '2024-02-01',
    imagePath: 'assets/images/6.jpg',
  ),
  Product(
    name: 'Sprite',
    barcode: '9876543210125',
    quantity: '90',
    category: 'Beverages',
    salePrice: '9 EGP',
    purchasePrice: '6 EGP',
    description: 'Lemon-Lime Soft Drink',
    expirationDate: '2024-03-01',
    imagePath: 'assets/images/3.jpeg',
  ),
  Product(
    name: 'Fanta',
    barcode: '9876543210126',
    quantity: '75',
    category: 'Beverages',
    salePrice: '10 EGP',
    purchasePrice: '7 EGP',
    description: 'Orange Flavored Soft Drink',
    expirationDate: '2024-04-01',
    imagePath: 'assets/images/5.jpeg',
  ),
  Product(
    name: 'Red Bull',
    barcode: '9876543210127',
    quantity: '50',
    category: 'Beverages',
    salePrice: '15 EGP',
    purchasePrice: '10 EGP',
    description: 'Energy Drink',
    expirationDate: '2024-05-01',
    imagePath: 'assets/images/2.jpeg',
  ),
  Product(
    name: 'Water',
    barcode: '9876543210128',
    quantity: '200',
    category: 'Beverages',
    salePrice: '5 EGP',
    purchasePrice: '3 EGP',
    description: 'Mineral Water',
    expirationDate: '2025-01-01',
    imagePath: 'assets/images/5.jpeg',
  ),
  Product(
    name: 'Lays Chips',
    barcode: '9876543210129',
    quantity: '150',
    category: 'Snacks',
    salePrice: '5 EGP',
    purchasePrice: '3.5 EGP',
    description: 'Potato Chips',
    expirationDate: '2024-06-01',
    imagePath: 'assets/images/6.jpg',
  ),
  Product(
    name: 'KitKat',
    barcode: '9876543210130',
    quantity: '120',
    category: 'Snacks',
    salePrice: '7 EGP',
    purchasePrice: '5 EGP',
    description: 'Chocolate Bar',
    expirationDate: '2024-07-01',
    imagePath: 'assets/images/2.jpeg',
  ),
  Product(
    name: 'Heinz Ketchup',
    barcode: '9876543210131',
    quantity: '100',
    category: 'Condiments',
    salePrice: '20 EGP',
    purchasePrice: '15 EGP',
    description: 'Tomato Ketchup',
    expirationDate: '2024-08-01',
    imagePath: 'assets/images/2.jpeg',
  ),
  Product(
    name: 'Pringles',
    barcode: '9876543210132',
    quantity: '100',
    category: 'Snacks',
    salePrice: '12 EGP',
    purchasePrice: '9 EGP',
    description: 'Potato Crisps',
    expirationDate: '2024-09-01',
    imagePath: 'assets/images/6.jpeg',
  ),
];


final List<Category> categories = [
  Category('Beverages'),
  Category('Snacks'),
  Category('Grocery'),
  Category('Fruits'),
  Category('Vegetables'),
  Category('Dairy'),
  Category('Meat'),
  Category('Bakery'),
  Category('Frozen Foods'),
  Category('Cereals'),
  Category('Condiments'),
  Category('Spices'),
  Category('Pasta'),
  Category('Confectionery'),
  Category('Drinks'),
  Category('Seafood'),
  Category('Delicatessen'),
  Category('Cheese'),
  Category('Cleaning Supplies'),
  Category('Pet Supplies'),
  Category('Personal Care'),
];